# Generated by Django 3.2.20 on 2023-08-31 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название картины (не более 100 символов).', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание картины (не обязательно).', verbose_name='О работе')),
                ('image', models.ImageField(help_text='Добавьте фотографию картины.', upload_to='', verbose_name='Изображение')),
                ('completion_date', models.DateField(help_text='Добавьте дату завершения работы над картиной.', verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('sl', 'В продаже'), ('sd', 'Продана'), ('ns', 'Не продаётся')], default='ns', help_text='Выбрать статус картины.', max_length=100, verbose_name='Статус')),
                ('price', models.IntegerField(help_text='Введите цену картины.', verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария.', verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
