# Generated by Django 3.2.20 on 2023-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.IntegerField(help_text='Введите цену картины.', null=True, verbose_name='Цена'),
        ),
    ]
