# Generated by Django 3.2.20 on 2023-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Добавьте фотографию картины.', upload_to='', verbose_name='Обложка статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Введите подзаголовок поста.', max_length=500, verbose_name='Подзаголовок'),
        ),
    ]
