# Generated by Django 3.2.20 on 2023-12-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='link_code',
            field=models.TextField(blank=True, help_text='Добавьте код из Ютуба.', verbose_name='Код для вставки видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='link_youtube',
            field=models.TextField(blank=True, help_text='Добавьте ссылку на видео.', verbose_name='Ссылка'),
        ),
    ]
